/*
 * @Author: Jake 
 * @Date: 2023-01-25 15:20:22
 * @LastEditors: Jake 
 * @LastEditTime: 2023-09-25 20:44:21
 * @FilePath: /bingxiang/my_app/lib/utils/global.dart
 * @Description: 
 * step是List<String>
 * 搜图网站: https://pic.sogou.com/pic/searchList.jsp?keyword=%E8%BE%A3%E7%82%92%E6%AF%9B%E8%B1%86%E7%B2%92&uID=00062B1F4C4573DA6418E4844FD92921&v=5&statref=searchlist_form&rcer=
 */

import 'package:my_app/utils/foodStorage.dart';

class Global {
  static bool hasShowAlert = false;
  static String notice = '';

  static List<Map> refrigeStorage = getRefrigeStorage();
  static List<Map> getRefrigeStorage() {
    List<Map> list = [];
    int index = 0;
    final List originalData = [
      {'type': '主食', 'data': FoodStroage.zhushi},
      {'type': '蔬菜', 'data': FoodStroage.vegitable},
      {'type': '肉类', 'data': FoodStroage.meat},
      {'type': '中性', 'data': FoodStroage.middle},
      {'type': '凉菜', 'data': FoodStroage.liangcai},
      {'type': '配料', 'data': FoodStroage.peiliao},
      {'type': '奶制品', 'data': FoodStroage.milk},
      {'type': '水果', 'data': FoodStroage.fruit},
    ];
    for (var i = 0; i < originalData.length; i++) {
      for (var j = 0; j < originalData[i]['data'].length; j++) {
        list.add({
          'id': index,
          'name': originalData[i]['data'][j],
          'type': originalData[i]['type'],
          'isSelected': false
        });
        index++;
      }
    }
    return list;
  }

  static List<Map> recipeData = [
    {
      "id": 0,
      "name": "番茄炒鸡蛋",
      "mainFood": ["鸡蛋", "番茄"],
      "support": [],
      "prepare": ['打蛋(2个鸡蛋配一个番茄)', '番茄切块'],
      "step": ['注意：2个鸡蛋糖要加2勺'],
      "seasoning": ["葱", "糖"],
      "type": "中性",
      "img":
          'https://chinatown.co.uk/wp-content/uploads/2016/08/tomato-egg-stir-fry.jpg'
    },
    {
      "id": 1,
      "name": "土豆炒青椒",
      "mainFood": ["土豆", "青椒", "蒜"],
      "support": [],
      "prepare": ['土豆切丝或片+泡水', '青椒切丝或块', '准备蒜末'],
      "step": ['热油炒青椒，加盐，盛出', '剩油加蒜末加土豆 翻炒均匀', "加盐，加生抽，翻炒均匀加青椒，翻炒均匀出锅"],
      "seasoning": ["葱", "酱油"],
      "type": "蔬菜",
      "img":
          'https://imgoss.ilive.cn/hc-web/uploads/newimg/20140808/534b94fe78b7d54d690416635d1079a6.jpg',
    },
    {
      "id": 2,
      "name": "蛋炒饭",
      "mainFood": ["鸡蛋", "剩饭"],
      "support": ['打蛋', '切葱花'],
      "prepare": [],
      "step": ['这还用教吗'],
      "seasoning": ["葱", "酱油"],
      "type": "主食",
      "img":
          'https://i3.meishichina.com/atta/recipe/2012/06/13/20120613191312344873986.jpg?x-oss-process=style/p800'
    },
    {
      "id": 3,
      "name": "蒜子鸡肉",
      "mainFood": ["鸡腿肉", "蒜"],
      "support": [],
      "prepare": [
        '鸡腿肉切块',
        '腌制20分钟： 鸡腿肉中加 1勺料酒，1勺生抽，1勺老抽，1勺耗油，1勺淀粉，1勺橄榄油，适量黑胡椒',
        '葱切末'
      ],
      "seasoning": [],
      "step": [
        '起锅烧油，蒜瓣小火煎香',
        '倒入腌制好的鸡腿肉 ',
        '翻炒均匀出锅，撒葱末摆盘',
      ],
      "type": "肉类",
      "img":
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTv4A4PtL41FK4y6SHQeWkqWTgfge6Bv6Ceg&usqp=CAU'
    },
    {
      "id": 4,
      "name": "番茄虾仁酸辣面",
      "mainFood": ["虾仁", "蒜", "番茄", "泡面面饼", "上海白", "火腿肠", "鸡蛋"],
      "support": [],
      "prepare": [
        '大虾拿出来解冻',
        '腌制10分钟：虾中放 1勺料酒，1丢丢盐，少量黑胡椒',
        '番茄切丁',
        '火腿肠切片',
        '上海白洗干净',
        '一个小碗准备好调料： 蒜末，辣椒面，白芝麻',
      ],
      "seasoning": [],
      "step": [
        '煎虾仁，盛出备用',
        '煎个温泉蛋',
        '热油下番茄丁，翻炒出汁，加入清水煮开',
        '下入泡面面饼和火腿肠，上海白，虾仁 煎蛋，煮着的时候做下一步',
        '热油，浇到准备好的调料上， 再加2勺生抽，1勺陈醋，1勺耗油，半勺糖，半勺盐',
        '把酱汁倒回泡面锅里，出锅',
      ],
      "type": "主食",
      "img": 'https://i03piccdn.sogoucdn.com/77407a7d6adf21a0'
    },
    {
      "id": 5,
      "name": "土豆烧豆角(非芸豆)",
      "mainFood": ["土豆", "蒜", "豆角"],
      "support": [],
      "prepare": [
        "土豆切粗条状",
        "豆角切段",
        "蒜末",
        "葱花",
        "小米辣段",
        "调料汁：生抽，老抽，耗油，淀粉，清水",
      ],
      "seasoning": [],
      "step": [
        "起锅烧油，豆角煎黄盛出备用",
        "起锅烧油，土豆煎黄，加入蒜末葱花小米辣，加入豆角",
        "加入调料汁，搅拌均匀，收汁出锅",
      ],
      "type": "蔬菜",
      "img": 'https://i02piccdn.sogoucdn.com/51bd858b9b334191'
    },
    {
      "id": 9,
      "name": "炒菜丝",
      "mainFood": ["包菜", "胡萝卜", "鸡蛋"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "蔬菜",
      "img": 'https://i04piccdn.sogoucdn.com/7a5d7a625d6b3a74'
    },
    {
      "id": 10,
      "name": "韩式午餐肉豆腐汤",
      "mainFood": ["午餐肉", "洋葱", "金针菇", "土豆", "老豆腐", "泡菜", "青椒", "红椒"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "中性",
      "img": 'https://i01piccdn.sogoucdn.com/03de4accf2484f38'
    },
    {
      "id": 11,
      "name": "脆皮麻油鸡",
      "mainFood": ["鸡腿肉"],
      "support": [],
      "prepare": [
        "姜切片",
        "腌制需要30分钟：鸡腿肉一大片不用切，放大碗，加姜片，1勺料酒，2勺生抽，1勺耗油，1大堆蒜，少许盐，少许黑胡椒，少许香油，",
      ],
      "seasoning": [],
      "step": [
        "鸡腿肉一大片不用切，放大碗，加姜片，1勺料酒，2勺生抽，1勺耗油，1大堆蒜，少许盐，少许黑胡椒，少许香油，抓匀，腌制半小时",
        "半小时后，裹上玉米淀粉",
        "烧热油(一层底就行），放鸡排，煎出脆皮转中火，时不时翻面，煎至两面金黄出锅，切块",
      ],
      "type": "肉类",
      "img": 'https://i03piccdn.sogoucdn.com/1d27e9e2fcdecd6f'
    },
    {
      "id": 12,
      "name": "香酥炸蟹柳",
      "mainFood": ["蟹肉棒"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "零食",
      "img": 'https://i04piccdn.sogoucdn.com/07f9ed7ddcf27640'
    },
    {
      "id": 13,
      "name": "番茄浓汤肥牛粉丝煲",
      "mainFood": ["肥牛卷", "番茄", "细粉丝"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "晚餐",
      "img": 'https://i02piccdn.sogoucdn.com/045e277e03c69bf1'
    },
    {
      "id": 14,
      "name": "左宗棠鸡",
      "mainFood": ["鸡腿肉", "鸡蛋", "青椒"],
      "needFried": true,
      "support": [],
      "prepare": [
        "鸡腿肉切小块",
        "腌制20分钟： 切好的鸡腿肉小块加1勺料酒，1勺生抽，少许盐，半个蛋清",
        "做调料汁： 1x勺生抽，1勺老抽，1勺白醋，1勺番茄酱，1勺淀粉，1勺白糖，半勺盐，加少量水",
        "青红椒切粒，没有红椒就小米辣",
        "蒜切末",
        "葱切末",
        "姜切片",
        "准备红干辣椒",
      ],
      "seasoning": [],
      "step": [
        "腌制好的鸡腿肉块加淀粉，搅拌均匀",
        "6成油 炸鸡块，炸至金黄，捞出沥干",
        "青红椒粒过一遍油， 也炸一下",
        "另起干净的锅，下蒜末爆香，加葱姜,加红干辣椒炒炒",
        "倒入炸好的鸡块",
        "加少量料酒",
        "加准备好的调料汁，炒到汤汁浓稠，放青红椒",
        "翻炒均匀淋少许香油，翻炒均匀，关火出锅",
      ],
      "type": "肉类",
      "img": 'https://i03piccdn.sogoucdn.com/fcfae78068372ee6'
    },
    {
      "id": 15,
      "name": "韭黄炒鸡蛋",
      "mainFood": ["韭黄", "鸡蛋"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "蔬菜",
      "img": 'https://i02piccdn.sogoucdn.com/79a09c56e5717b87'
    },
    {
      "id": 16,
      "name": "黑椒芦笋口蘑",
      "mainFood": ["芦笋", "口蘑"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "蔬菜",
      "img": 'https://i02piccdn.sogoucdn.com/a8442d0556a3047b'
    },
    {
      "id": 17,
      "name": "番茄浓汤排骨",
      "mainFood": ["番茄", "排骨"],
      "time": '至少40分钟',
      "support": [],
      "prepare": [
        '番茄切块',
        '一个小碗放： 葱姜蒜，冰糖，桂皮八角',
        '锅中冷水下入排骨，料酒，焯水',
        '煮开热水(排骨汤备用)',
      ],
      "seasoning": [],
      "step": [
        '起锅烧油下入姜葱蒜少许冰糖，八角桂皮，倒入焯水后的排骨',
        '加入 两勺生抽，一勺老抽，一勺耗油，翻炒均匀',
        '加热水煮开',
        '另起锅烧油炒番茄出汁，加一勺番茄酱，倒入排骨汤锅',
        '小火炖40分钟',
        '撒葱花出锅',
      ],
      "type": "肉类",
      "img": 'https://i01piccdn.sogoucdn.com/31a3f04d678d990c'
    },
    {
      "id": 19,
      "name": "鱼香杏鲍菇",
      "mainFood": [
        "杏鲍菇",
        "白萝卜",
        "青椒",
        "红椒",
        "木耳",
      ],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "蔬菜",
      "img": 'https://i03piccdn.sogoucdn.com/85c4adb4dc13ca03'
    },
    {
      "id": 20,
      "name": "茄汁日本豆腐",
      "mainFood": ["日本豆腐", "番茄", "金针菇", "红椒", "木耳"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "中性",
      "img": 'https://i01piccdn.sogoucdn.com/fdde66ea4649835d'
    },
    {
      "id": 21,
      "name": "牛肉粒炒青椒",
      "mainFood": ["牛肉", "蒜", "彩椒", "洋葱"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "肉类",
      "img": 'https://i01piccdn.sogoucdn.com/b3d7c43c7e379919'
    },
    {
      "id": 22,
      "name": "神仙蛋炒饭",
      "mainFood": ["午餐肉", "鸡蛋", "剩饭", "三色粒", "海苔碎"],
      "support": [],
      "prepare": [
        "午餐肉切粒",
        "打2个鸡蛋准备好",
        "三色粒拿出来化一下",
      ],
      "seasoning": [],
      "step": ["随便做做"],
      "type": "主食",
      "img": 'https://i01piccdn.sogoucdn.com/1a6ca101b51a3bae'
    },
    {
      "id": 23,
      "name": "肥牛虾滑响铃卷",
      "mainFood": ["响铃卷", "肥牛卷", "虾滑", "番茄"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "肉类",
      "img": 'https://i01piccdn.sogoucdn.com/eb47ca103dd42537'
    },
    {
      "id": 24,
      "name": "啫啫鸡煲",
      "mainFood": ["鸡腿肉", "洋葱", "白酒", "香菜"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "肉类",
      "img": 'https://i04piccdn.sogoucdn.com/34648e4681ffe506'
    },
    {
      "id": 25,
      "name": "海苔虾滑饼",
      "mainFood": ["海苔", "虾滑", "三色粒"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "零食",
      "img": 'https://i02piccdn.sogoucdn.com/5cdef94f2bc9344f'
    },
    {
      "id": 26,
      "name": "鸡公煲",
      "mainFood": ["鸡腿肉", "洋葱", "青椒", "莴笋", "泡面面饼"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "肉类",
      "img": 'https://i01piccdn.sogoucdn.com/b5ef293798c6eb78'
    },
    {
      "id": 26,
      "name": "烧肥牛卷",
      "mainFood": ["肥牛卷", "洋葱", "香菜"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "肉类",
      "img": 'https://i03piccdn.sogoucdn.com/ddd67b7dd45f2e5b'
    },
    {
      "id": 27,
      "name": "蛤喇抱蛋",
      "mainFood": ["蚬子肉", "鸡蛋"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "肉类",
      "img": 'https://i01piccdn.sogoucdn.com/0fe88838343cc160'
    },
    {
      "id": 28,
      "name": "葱油焖鸡",
      "mainFood": ["鸡腿肉"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "肉类",
      "img": 'https://i01piccdn.sogoucdn.com/eee3f2df898359d5'
    },
    {
      "id": 29,
      "name": "烧烤牛肉丸",
      "mainFood": ["牛肉丸"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "零食",
      "img": 'https://i03piccdn.sogoucdn.com/1ead5669ae18d412'
    },
    {
      "id": 30,
      "name": "地狱排骨煲",
      "mainFood": ["排骨", "土豆", "胡萝卜", "玉米", "香菇"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "肉类",
      "img": 'https://i03piccdn.sogoucdn.com/6e268c60d5698b5f'
    },
    {
      "id": 31,
      "name": "麻辣水煮肉片",
      "mainFood": ["里脊肉", "莴笋", "金针菇", "豆芽"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "肉类",
      "img": 'https://i01piccdn.sogoucdn.com/e36680801f75937a'
    },
    {
      "id": 32,
      "name": "番茄浓汤肥牛炸蛋",
      "mainFood": ["番茄", "肥牛卷", "鸡蛋"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "肉类",
      "img": 'https://i02piccdn.sogoucdn.com/9315021fa01006df'
    },
    {
      "id": 33,
      "name": "葱烧豆腐",
      "mainFood": ["京葱", "老豆腐"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "中性",
      "img": 'https://i02piccdn.sogoucdn.com/b9503bbf8b9680ec'
    },
    {
      "id": 34,
      "name": "抱蛋豆腐",
      "mainFood": ["嫩豆腐", "鸡蛋", "火腿肠"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "中性",
      "img": 'https://i02piccdn.sogoucdn.com/28b3a88d2d1b7eca'
    },
    {
      "id": 35,
      "name": "酸汤水饺",
      "mainFood": ["饺子", "紫菜", "虾米"],
      "support": [],
      "prepare": ['切葱花', '蒜切末'],
      "seasoning": [],
      "step": [
        '饺子煮熟捞出',
        "做辣子油: 白芝麻，葱花，蒜末，辣椒面，撒上热油",
        "所有东西倒在一起，加两勺生抽，一勺白醋，一勺耗油，少许盐，紫菜，虾米 搅拌即可",
      ],
      "type": "主食",
      "img": 'https://i02piccdn.sogoucdn.com/f221130ef94fe452'
    },
    {
      "id": 36,
      "name": "肉酱拌面",
      "mainFood": ["肉末", "黄瓜", "手擀面"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "主食",
      "img": 'https://i02piccdn.sogoucdn.com/4d9e24b9ccdc3007'
    },
    {
      "id": 37,
      "name": "酸辣麻酱拌面",
      "mainFood": ["花生米", "黄瓜", "手擀面", "香菜"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "主食",
      "img": 'https://i03piccdn.sogoucdn.com/65fac1570368173c'
    },
    {
      "id": 38,
      "name": "油泼面",
      "mainFood": ["手擀面", "蒜", "上海白"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "主食",
      "img": 'https://i01piccdn.sogoucdn.com/96507b75ba8e8e08'
    },
    {
      "id": 39,
      "name": "番茄鸡蛋打卤面",
      "mainFood": ["手擀面", "番茄", "鸡蛋", "蒜"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "主食",
      "img": 'https://i02piccdn.sogoucdn.com/b28c1157bd91553d'
    },
    {
      "id": 40,
      "name": "黄磊同款拌面",
      "mainFood": ["手擀面", "雪碧", "蒜", "黄瓜", "胡萝卜"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "主食",
      "img": 'https://i01piccdn.sogoucdn.com/0549e2f55d5ca1b6'
    },
    {
      "id": 41,
      "name": "荷包蛋焖面",
      "mainFood": ["手擀面", "鸡蛋", "蒜"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "主食",
      "img": 'https://i02piccdn.sogoucdn.com/3605c2747303ec3c'
    },
    {
      "id": 42,
      "name": "耗油芥蓝",
      "mainFood": ["芥蓝", "蒜"],
      "support": [],
      "prepare": ['煮开水（煮芥蓝）', '清洗芥蓝', '蒜切末', '调汁碗：一勺耗油，一勺酱油，蒜末一把'],
      "seasoning": [],
      "step": [
        '煮开水',
        '煮芥蓝（3分钟）',
        '调汁： 一勺耗油，一勺酱油，蒜末一把',
        '摆盘，倒入调汁，小火烧橄榄油，浇到蒜末上',
      ],
      "type": "蔬菜",
      "img":
          'https://www.wecook123.com/wp-content/uploads/2017/05/%E8%A0%94%E6%B2%B9%E8%8A%A5%E8%97%8D_aow2jn1P38.JPG',
    },
    {
      "id": 43,
      "name": "芥蓝腊肠炒饭",
      "mainFood": ["芥蓝", "火腿肠"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "主食",
      "img": 'https://i02piccdn.sogoucdn.com/a1a5d11931d3c954'
    },
    {
      "id": 44,
      "name": "茼蒿豆腐煲",
      "mainFood": ["茼蒿", "嫩豆腐"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "蔬菜",
      "img": 'https://i02piccdn.sogoucdn.com/69e29c8b2dc650fd'
    },
    {
      "id": 45,
      "name": "蒜香耗油茼蒿",
      "mainFood": ["茼蒿", "蒜"],
      "support": [
        "茼蒿洗干净，对切",
        "蒜切末",
        "干辣椒切段",
      ],
      "prepare": [],
      "seasoning": [],
      "step": [
        "热油放蒜末干辣椒爆香",
        "加入茼蒿翻炒均匀",
        "加2勺生抽，1勺耗油",
        "翻炒至微微出汁出锅",
      ],
      "type": "蔬菜",
      "img": 'https://i02piccdn.sogoucdn.com/4c45fa7bc67ba37c'
    },
    {
      "id": 46,
      "name": "茼蒿炒鸡蛋",
      "mainFood": ["茼蒿", "鸡蛋", "蒜"],
      "support": [],
      "prepare": [
        "打两个鸡蛋",
        "蒜切末",
        "干辣椒切段",
        "茼蒿洗干净切小段",
      ],
      "seasoning": [],
      "step": [
        "起锅烧油炒鸡蛋，盛出备用",
        "热油放蒜末，干辣椒段炒香，倒入茼蒿炒至五分熟",
        "倒入炒好的鸡蛋，加1勺生抽，1勺耗油，适量盐，翻炒均匀即可"
            "盐不均匀的话，沿锅边倒一小碗水，焖上，盐就化了",
      ],
      "type": "蔬菜",
      "img": 'https://i04piccdn.sogoucdn.com/25f1acd1e2449ab7'
    },
    {
      "id": 47,
      "name": "魔芋丝拌木耳",
      "mainFood": ["木耳", "魔芋丝", "香菜"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "减脂",
      "img": 'https://i03piccdn.sogoucdn.com/910b751c169607f7'
    },
    {
      "id": 48,
      "name": "虾滑魔芋丝",
      "mainFood": ["魔芋丝", "虾滑", "香菜", "蒜", "洋葱"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "减脂",
      "img": 'https://i02piccdn.sogoucdn.com/7a9b8f83657a09dc'
    },
    {
      "id": 49,
      "name": "酸汤魔芋丝",
      "mainFood": ["魔芋丝", "西红柿", "蒜", "鸡蛋"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "减脂",
      "img": 'https://i03piccdn.sogoucdn.com/4060cfe246361de8'
    },
    {
      "id": 50,
      "name": "凉拌魔芋丝",
      "mainFood": ["魔芋丝", "花生米", "黄瓜", "鸡蛋"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "减脂",
      "img": 'https://i02piccdn.sogoucdn.com/b7eef948e5f5bdfd'
    },
    {
      "id": 51,
      "name": "金针菇肥牛粉丝煲",
      "mainFood": ["肥牛卷", "粉丝", "洋葱", "金针菇"],
      "support": [],
      "prepare": [
        '煮开水(煮肥牛卷)',
        '肥牛卷化了',
        '粉丝泡水',
        '金针菇清洗切根',
        '洋葱切条',
        '小米辣切碎',
        '调个酱汁：整头蒜末切碎，热油浇，以下都2倍： 加2勺生抽，半勺老抽，一勺耗油，半勺白糖，一小勺胡椒粉，适量盐',
      ],
      "seasoning": [],
      "step": [
        '煮热水',
        '开水烫下肥牛卷',
        '砂锅底铺一层洋葱，金针菇，粉丝，肥牛卷，淋上调好的酱汁，再加一碗水，盖盖效果焖5-6分钟即可',
        '撒上葱花和小米辣'
      ],
      "type": "汤类",
      "img": 'https://i02piccdn.sogoucdn.com/2bcd75f6a410e337'
    },
    {
      "id": 52,
      "name": "辣椒炒豆泡",
      "mainFood": ["青椒", "豆泡", "蒜"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "中性",
      "img": 'https://i02piccdn.sogoucdn.com/7c48c987eda6a9fd'
    },
    {
      "id": 53,
      "name": "豆泡蒸肉",
      "mainFood": ["豆泡", "肉末", "香菇", "蒜"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "肉类",
      "img": 'https://i01piccdn.sogoucdn.com/13e18cfc139cd5ff'
    },
    {
      "id": 53,
      "name": "豆芽焖豆泡",
      "mainFood": ["豆泡", "豆芽", "洋葱", "青椒"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "中性",
      "img": 'https://i02piccdn.sogoucdn.com/90f93e9bf9b6c387'
    },
    {
      "id": 54,
      "name": "豆泡酿虾滑",
      "mainFood": ["豆泡", "虾滑"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "中性",
      "img": 'https://i01piccdn.sogoucdn.com/2da2b81f75ed0f81'
    },
    {
      "id": 55,
      "name": "蒜香口蘑鸡",
      "mainFood": ["口蘑", "蒜", "鸡腿肉"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "肉类",
      "img": 'https://i03piccdn.sogoucdn.com/9b681c109d6b76c7'
    },
    {
      "id": 57,
      "name": "口蘑虾滑",
      "mainFood": ["口蘑", "虾滑"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "中性",
      "img": 'https://i02piccdn.sogoucdn.com/a2338d901b0e8cec'
    },
    {
      "id": 58,
      "name": "爆炒鱿鱼卷",
      "mainFood": ["鱿鱼卷", "青椒", "红椒", "洋葱"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "肉类",
      "img": 'https://i01piccdn.sogoucdn.com/82642890a3049fc6'
    },
    {
      "id": 59,
      "name": "家常爆炒鱿鱼卷",
      "mainFood": ["鱿鱼卷", "青椒", "胡萝卜", "木耳"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "肉类",
      "img": 'https://i02piccdn.sogoucdn.com/a0ecc8af48f5f0d8'
    },
    {
      "id": 60,
      "name": "家庭版香辣鱿鱼",
      "mainFood": ["鱿鱼须", "青椒", "红椒", "洋葱"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "肉类",
      "img": 'https://i02piccdn.sogoucdn.com/94173b4e17ff2db0'
    },
    {
      "id": 61,
      "name": "辣炒毛豆粒",
      "mainFood": ["毛豆粒", "青椒", "红椒", "蒜"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "蔬菜",
      "img": 'https://i02piccdn.sogoucdn.com/a9291a33febd7acc'
    },
    {
      "id": 62,
      "name": "五花肉炒毛豆粒",
      "mainFood": ["五花肉", "毛豆粒", "蒜"],
      "support": [],
      "prepare": [
        "毛豆拿出来化",
        "五花肉切小长条",
        "葱切末",
        "蒜切末",
        "小米辣切段",
        "青椒切碎块（可有可无）",
      ],
      "seasoning": [],
      "step": [
        "起锅热油，加毛豆粒 和少许盐，炒3分钟，盛出",
        "剩余油，放五花肉，翻炒出油",
        "加葱末，蒜末，小米辣，料酒，少许老抽",
        "大火炒香，下毛豆，加生抽，耗油",
        "大火翻炒5分钟 + 青椒碎，小葱段翻炒均匀即可",
      ],
      "type": "肉类",
      "img": 'https://i01piccdn.sogoucdn.com/c1b4b9895ba06440'
    },
    {
      "id": 63,
      "name": "毛豆火腿炒饭",
      "mainFood": ["剩饭", "毛豆粒", "火腿肠"],
      "step": [],
      "prepare": [],
      "support": [],
      "seasoning": [],
      "type": "主食",
      "img": 'https://i02piccdn.sogoucdn.com/b4055c2e542f507c'
    },
    {
      "id": 64,
      "name": "土豆卤肉饭",
      "mainFood": ["剩饭", "土豆", "五花肉", "洋葱"],
      "support": [],
      "time": '30分钟以上',
      "step": [
        "锅中不放油，干煸五花肉，炸到金黄，盛出五花肉",
        "用剩余油炸洋葱，炸到金黄，捞出",
        "用剩余油炸土豆，炸到金黄，捞出",
        "葱姜爆香，放入炸好的五花肉，洋葱， 加2勺料酒，2勺生抽，1勺耗油，桂皮，香叶，八角，冰糖，翻炒片刻",
        "加一碗开水，小火炖30分钟",
        "加盐 再炖5分钟，出锅",
      ],
      "prepare": [
        "土豆切小粒",
        "洋葱切小块",
        "五花肉切小条",
        "准备个碗放：桂皮，香叶，八角，冰糖",
        "煮开水(卤肉汤用)",
      ],
      "seasoning": [],
      "type": "主食",
      "img": 'https://i02piccdn.sogoucdn.com/a16400183b7b433c'
    },
    {
      "id": 65,
      "name": "毛豆炒鸡蛋",
      "mainFood": ["毛豆粒", "鸡蛋", "青椒"],
      "support": [],
      "prepare": [
        '毛豆粒拿出来化',
        '青椒切小块',
        '葱切末',
        '打3个鸡蛋，放少许盐',
      ],
      "seasoning": [],
      "step": [
        '起锅热油，油温五成热下毛豆仁，生炒变绿了时候放盐，炒2分钟',
        '放入葱花和青椒翻炒均匀，锅底摊平',
        '往里面铺鸡蛋(像摊鸡蛋饼那样)',
        '鸡蛋凝结后翻面，翻炒出锅',
      ],
      "type": "中性",
      "img": 'https://i02piccdn.sogoucdn.com/2eaa0e9dab0205fd'
    },
    {
      "id": 66,
      "name": "椒盐玉米粒",
      "mainFood": ["玉米粒"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "中性",
      "img": 'https://i02piccdn.sogoucdn.com/a4376e900d94680b'
    },
    {
      "id": 67,
      "name": "奶香玉米浓汤",
      "mainFood": ["玉米粒", "胡萝卜", "口蘑", "火腿肠", "牛奶"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "汤类",
      "img": 'https://i02piccdn.sogoucdn.com/662c60f103c45693'
    },
    {
      "id": 68,
      "name": "黄金玉米烙",
      "mainFood": ["玉米粒"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "中性",
      "img": 'https://i02piccdn.sogoucdn.com/bd2a7211a4a86c2f'
    },
    {
      "id": 69,
      "name": "土豆肥牛饭",
      "mainFood": ["土豆", "肥牛卷", "青椒", "小米辣", "蒜"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "主食",
      "img": 'https://i01piccdn.sogoucdn.com/ca8ed6d23005bc7f'
    },
    {
      "id": 70,
      "name": "红烧土豆",
      "mainFood": ["土豆", "蒜"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "中性",
      "img": 'https://i01piccdn.sogoucdn.com/ea4d19afb100a3af_adv'
    },
    {
      "id": 71,
      "name": "干煸土豆",
      "mainFood": ["土豆", "干辣椒", "蒜"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "中性",
      "img": 'https://i01piccdn.sogoucdn.com/6ea5db1ea0fcbb8f_adv'
    },
    {
      "id": 72,
      "name": "肉末土豆",
      "mainFood": ["土豆", "肉末", "小米辣", "蒜"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "中性",
      "img": 'https://i01piccdn.sogoucdn.com/2e25facb77bd5743_adv'
    },
    {
      "id": 73,
      "name": "可乐鸡翅焖土豆",
      "mainFood": ["土豆", "鸡翅", "雪碧"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "肉类",
      "img": 'https://i03piccdn.sogoucdn.com/be4eed3a97875d1a'
    },
    {
      "id": 74,
      "name": "香酥虾仁",
      "mainFood": ["虾仁"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "中性",
      "img": 'https://i04piccdn.sogoucdn.com/21dd39ee41d5e969'
    },
    {
      "id": 75,
      "name": "香酥椒盐排骨",
      "mainFood": ["排骨", "蒜"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "肉类",
      "img": 'https://i01piccdn.sogoucdn.com/4cad883e07e5e340_adv'
    },
    {
      "id": 76,
      "name": "黄豆炖猪蹄",
      "mainFood": ["猪蹄", "啤酒", "黄豆"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "肉类",
      "img": 'https://i01piccdn.sogoucdn.com/2a406f8d34449734_adv'
    },
    {
      "id": 77,
      "name": "蒜香茄子",
      "mainFood": ["茄子", "蒜"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "蔬菜",
      "img": 'https://i03piccdn.sogoucdn.com/ad055a7c4fbb6063'
    },
    {
      "id": 78,
      "name": "干锅土豆",
      "mainFood": ["土豆", "五花肉", "青椒", "小米辣", "蒜", "洋葱"],
      "support": [],
      "prepare": [],
      "seasoning": [],
      "step": [],
      "type": "肉类",
      "img": 'https://i01piccdn.sogoucdn.com/8418879690ecfc07_adv'
    },
    {
      "id": 79,
      "name": "粉丝蒜蓉虾",
      "mainFood": ["虾仁", "粉丝", "蒜", "小米辣", "蒜蓉酱"],
      "support": [],
      "prepare": [
        '粉丝泡软',
        '小米辣切末',
        '葱切末',
        '大虾切花刀，交叉过去立起',
        '调汁： 蒜末，小米辣末，生抽，耗油，淋热油 搅拌均匀',
      ],
      "seasoning": [],
      "step": [
        '泡软的粉丝卷成圈',
        '大虾立在粉丝中间',
        '淋上调料汁，淋上蒜蓉酱',
        '大火蒸5分钟',
        '淋少许蒸鱼豉油，撒上葱花',
      ],
      "type": "中性",
      "img": 'https://i02piccdn.sogoucdn.com/f8aba59fe12b11ac'
    },
    {
      "id": 80,
      "name": "番茄牛腩(少汁甜口)",
      "mainFood": ["番茄", "牛腩", "香菜"],
      "support": [],
      "prepare": [
        '牛腩切块',
        '番茄切块',
        '葱切片',
        '姜切片',
        '香菜切末',
        '一个小碗放：干辣椒，八角，桂皮，香叶，干山楂，葱，姜',
      ],
      "time": '2小时',
      "seasoning": ['葱', "姜", "八角", "香叶", "桂皮", "冰糖", "干山楂", "红辣椒"],
      "step": [
        '牛腩冷水下锅，加葱姜，料酒，大火煮开',
        '准备一壶开水(保证牛肉不硬)',
        '撇去浮末，捞出冲洗干净',
        '炒锅预热，加油，小火，下冰糖炒至焦糖色，下牛腩炒上色',
        '加一勺生抽，一勺老抽，一勺耗油，干辣椒，八角，桂皮，香叶，干山楂，葱姜，大火翻炒均匀',
        '倒入一半番茄，加入没过牛肉的开水大火煮开转小火，炖一个半小时',
        '最后加盐调味，剩下一半番茄倒入炖10分钟，至汤汁浓稠，放香菜'
      ],
      "type": "肉类",
      "img": 'https://i04piccdn.sogoucdn.com/6fa01163b06d742f'
    },
    {
      "id": 81,
      "name": "拔丝地瓜",
      "mainFood": ["地瓜"],
      "support": [],
      "time": '30分钟',
      "prepare": ['地瓜切块'],
      "seasoning": [],
      "step": [
        '先炸地瓜，油锅六成热，放切块地瓜炸到地瓜里没有水分了',
        '锅中倒少量水，大量糖，大火炒，炒到吐沫沫调到7炒，(温度太低会翻砂)',
        '炒到很多泡泡，刚开始白色，后来会很快速转化成焦黄色，下炸好的地瓜，关火，搅拌均匀即可'
            '备注： 翻砂了是因为太凉了，'
      ],
      "type": "零食",
      "img": 'https://i04piccdn.sogoucdn.com/e31efba2d2eb6660'
    },
    {
      "id": 82,
      "name": "番茄牛腩(多汁)",
      "mainFood": ["番茄", "牛腩", "香菜"],
      "support": [],
      "prepare": [
        '牛腩切块泡水',
        '番茄切块',
        '葱切片',
        '姜切片',
        '香菜切末',
        '一个小碗放：葱，姜，蒜，桂皮，八角，香叶',
        '煮开水(牛腩汤用)',
      ],
      "time": '2小时',
      "seasoning": ['葱', "姜", "八角", "香叶", "桂皮"],
      "step": [
        '牛腩冷水下锅，加葱姜，料酒，大火煮开',
        '准备一壶开水(保证牛肉不硬)',
        '撇去浮末，捞出冲洗干净',
        '炒锅热油，爆香葱姜蒜，桂皮八角香叶，然后下入牛腩翻炒均匀',
        '加2勺料酒，2勺生抽，半勺老抽，热水没过肉,煮45分钟',
        '45分钟后 另起油锅，下番茄炒均匀，加入适量番茄酱，倒入牛肉锅 再煮45分钟',
        '大火收汁，加香菜，按照酸甜度放番茄酱或糖，咸度不够放盐，',
        '摆盘，撒葱花'
      ],
      "type": "肉类",
      "img": 'https://i04piccdn.sogoucdn.com/82b16983d49ab8b0'
    },
    {
      "id": 83,
      "name": "黄磊红烧肉",
      "time": '1小时以上',
      "mainFood": ["五花肉"],
      "support": [],
      "prepare": ['姜切块', '准备冰糖', '五花肉切块', '煮开水(煮五花肉用)'],
      "seasoning": [],
      "step": [
        "五花肉切大块，不要汆水",
        "热油(不要太多油，五花肉也出油)下肉块，煸炸到焦黄",
        "煮开水",
        "倒开水(原文倒黄酒...)，没过肉，加2块姜，适量盐，适量酱油",
        "小火炖一小时",
        "加入冰糖翻炒，炒出焦糖色 出锅",
      ],
      "type": "肉类",
      "img": 'https://i01piccdn.sogoucdn.com/c75ee30535630262'
    },
    {
      "id": 84,
      "name": "糖醋里脊",
      "type": "肉类",
      "img": 'https://i01piccdn.sogoucdn.com/502112cbb845191b',
      "mainFood": ["鸡腿肉", "面粉", "泡打粉"],
      "step": [
        "鸡腿肉切条，加盐，料酒，胡椒粉 腌制十分钟",
        "调一碗面糊： 3大少面粉，1勺土豆淀粉，小半勺泡打粉和一小撮盐",
        "少量多次加入清水调成糊浆状，不能太稀",
        "鸡腿肉倒入糊糊里挂浆",
        "7成热热油炸鸡条，炸到金黄捞出，升高温复炸30秒捞出",
        "起锅烧油，放3勺番茄酱，少量清水，2勺白糖，1勺白醋，少量水淀粉勾芡，倒入鸡条翻炒几下",
        "出锅前淋些油会颜色更亮",
        "摆盘 撒白芝麻和葱末"
      ],
      "needFried": true, //需要大量油炸
      "prepare": ['鸡腿肉切条', '准备面糊 3大少面粉，1勺土豆淀粉，小半勺泡打粉和一小撮盐', '葱切末'],
      "support": [],
      "seasoning": [],
    },
    {
      "id": 85,
      "name": "椰芒波波冰麻薯",
      "mainFood": [
        "椰奶",
        "木薯淀粉",
        "牛奶",
        "芒果",
      ],
      "support": [],
      "prepare": [
        "120g椰奶",
        "20g糖",
        "150g木薯淀粉",
        "200g牛奶",
        "一大碗凉水",
        "15g糖",
        "20g木薯淀粉",
        "芒果切块(奶昔用)",
        "芒果切小方块(摆盘用)",
        "果汁搅拌机",
        "面粉搅拌机",
      ],
      "seasoning": [],
      "step": [
        "锅里倒入120g椰奶和20g糖，煮开趁热倒入150g木薯淀粉里",
        "煮一锅开水一会热用，准备一大碗冰水",
        "揉成面团，搓成一颗颗小球",
        "水开把小球煮至浮起，捞出过冰水备用",
        "锅中加200g牛奶，15g糖，20g木薯淀粉，开小火不停搅拌，煮至浓稠拉丝，放冰箱冷藏备用",
        "切块的芒果放入搅拌机，倒入适量牛奶，打成奶昔",
        "摆盘： 碗中倒入奶昔，放入冰麻薯，啵啵球，芒果块",
      ],
      "type": "甜品",
      "img": 'https://i04piccdn.sogoucdn.com/5f76844a8001795a'
    },
    {
      "id": 86,
      "name": "辣子鸡丁",
      "type": "肉类",
      "img": 'https://i03piccdn.sogoucdn.com/28ddb13f6e610525',
      "needFried": true,
      "mainFood": [
        "鸡腿肉",
      ],
      "prepare": [
        "鸡腿肉切块",
        "姜切片",
        "腌制鸡腿肉20分钟：切块的鸡腿肉加 姜片，1勺料酒，1勺生抽，1勺老抽，1勺耗油，半勺白胡椒粉，少许盐，1勺淀粉",
        "蒜末",
        "花椒",
        "葱末",
        "一大堆干辣椒段"
      ],
      "step": [
        "腌制好的鸡腿肉下油锅炸至金黄，捞出复炸一次",
        "起锅烧油，加入蒜末花椒干辣椒炒香，倒入鸡丁炒均匀，加入一勺白芝麻",
        "撒上葱花翻炒均匀即可",
      ],
      "seasoning": [],
      "support": [],
    },
    {
      "id": 87,
      "name": "牛肉拌饭",
      "type": "主食",
      "img": 'https://i01piccdn.sogoucdn.com/30c6f8755e839140',
      "prepare": [
        "牛肉拿出来化了",
        "牛肉切片，腌制15分钟： 加入1勺料酒，生抽，耗油，淀粉",
        "小米辣切碎",
        "青椒切碎",
        "调个料汁：碗中放蒜末，小米辣，青椒碎，淋热油，再加2勺生抽，1勺耗油，1勺白糖",
        "生菜切丝",
      ],
      "step": [
        "热油，煎2个荷包蛋盛出备用",
        "热油放牛肉片炒熟备用",
        "摆盘：放米饭，放荷包蛋，牛肉片，生菜丝，海苔碎，淋上调料汁，搅拌均匀",
      ],
      "mainFood": [
        "牛肉",
        "青椒",
        "生菜",
        "鸡蛋",
        "剩饭",
        "海苔碎",
      ],
      "seasoning": [],
      "support": [],
    },
    {
      "id": 88,
      "name": "香菜拌肥牛卷",
      "type": "肉类",
      "img": 'https://i01piccdn.sogoucdn.com/287463b75dd468ee',
      "mainFood": [
        "香菜",
        "牛肉",
      ],
      "prepare": [
        "牛肉薄片 腌制15分钟： 加入半勺盐，半勺老抽，2勺生抽，2勺葱姜水，半勺白胡椒粉，1勺淀粉，搅拌均匀，再放2勺食用油",
        "调汁： 小碗放入： 2勺蒜末，2勺葱花，2勺小米辣圈，2勺白芝麻，2勺辣椒面，淋上热油，2勺陈醋，2勺生抽",
        "香菜切段",
      ],
      "step": [
        "将牛肉片下沸水锅中煮1分钟后，捞出放入大碗，加香菜段，淋上料汁，开吃",
      ],
      "seasoning": [],
      "support": [],
    },
    {
      "id": 89,
      "name": "农家一碗香",
      "type": "肉类",
      "img": 'https://i02piccdn.sogoucdn.com/2a5f59031ba311c1',
      "mainFood": [
        "猪瘦肉",
        "鸡蛋",
        "青椒",
      ],
      "prepare": [
        "猪瘦肉切片",
        "打3个鸡蛋",
        "青椒切丝",
        "红椒切丝(可有可无)",
        "小米辣切段",
      ],
      "step": [
        "热油炒鸡蛋，盛出备用",
        "热油煎肉片，至变色，加入小米辣，蒜末，1勺老干妈，翻炒均匀",
        "加入鸡蛋，1勺生蚝，1勺生抽，少许盐和黑胡椒粉，翻炒均匀",
        "放入葱段，青辣椒，翻炒均匀",
      ],
      "seasoning": [],
      "support": [],
    },
    {
      "id": 90,
      "name": "蒜香肉粒",
      "type": "肉类",
      "img": 'https://i03piccdn.sogoucdn.com/5774115953a5646d',
      "mainFood": [
        "猪瘦肉",
        "青椒",
      ],
      "prepare": [
        "猪肉切块，腌制15分钟： 1勺料酒，1勺生抽，半勺老抽，1勺耗油，半勺黑胡椒，食用油，半勺淀粉",
        "青椒切块",
        "红椒切块(可有可无)",
        "准备完整蒜肉",
      ],
      "step": [
        "起锅烧油，倒入蒜瓣，小火炒至表皮微焦，盛出备用",
        "倒入肉粒，炒熟后倒入蒜瓣，青红椒，翻炒均匀出锅",
      ],
      "seasoning": [],
      "support": [],
    },
    {
      "id": 91,
      "name": "火锅鸡",
      "type": "肉类",
      "img": 'https://i03piccdn.sogoucdn.com/9adb79d1977a77b6',
      "mainFood": ["鸡腿肉", "火锅底料", "啤酒", "青椒", "土豆", "洋葱", "小米辣", "香菜"],
      "prepare": [
        "青椒切段",
        "土豆切块泡水",
        "洋葱切块",
        "鸡腿肉洗干净炮去血水，切大块",
        "腌制鸡腿肉20分钟： 加入生抽，料酒，少量白胡椒粉",
        "小碗放 葱段，姜片，洋葱，八角，小米辣段，一小块火锅底料",
        "香菜切段",
      ],
      "step": [
        "起锅烧油，放入腌制好的鸡腿肉，炒熟盛出备用",
        "起锅烧油，放入准备好的八角葱姜小米辣洋葱火锅底料，翻炒均匀倒入刚炒好的鸡腿块",
        "炒香后倒入一听啤酒",
        "盖上锅盖等锅烧开",
        "开锅后加入生抽，盐，鸡精，耗油，白糖，盖上锅盖咕噜10分钟",
        "下入土豆块和青椒段，在咕噜5分钟",
        "撒一把香菜出锅",
      ],
      "seasoning": [],
      "support": [],
    },
    {
      "id": 92,
      "name": "芦笋虾仁",
      "type": "蔬菜",
      "img": 'https://i02piccdn.sogoucdn.com/6fd09acd7da12f30',
      "mainFood": [
        "虾仁",
        "口蘑",
        "芦笋",
      ],
      "prepare": [
        "煮开水(焯水用)",
        "虾切块 腌制5分钟： 去壳去虾线加入葱姜，一勺料酒，一勺生抽，适量黑胡椒",
        "口蘑切片",
        "准备完整蒜粒",
      ],
      "step": [
        "芦笋切块，焯水2分钟",
        "起锅烧油 虾炒变色，盛出备用",
        "起锅烧油，加入 蒜粒，口蘑炒香，倒入芦笋虾仁炒均匀",
        "加2勺生抽，1勺耗油，适量黑胡椒，翻炒均匀即可",
      ],
      "seasoning": [],
      "support": [],
    },
    {
      "id": 93,
      "name": "香辣蒜泥鸡爪",
      "type": "肉类",
      "time": '至少30分钟',
      "img": 'https://i03piccdn.sogoucdn.com/5421ca426f97007f',
      "mainFood": [
        "鸡爪",
        "小米辣",
      ],
      "prepare": [
        "小米辣切段",
        "蒜切末",
        "葱切段",
        "姜切片",
      ],
      "step": [
        "鸡爪冷水下锅，放入葱姜，料酒焯水，盛出备用",
        "起锅烧油，爆香蒜泥和小米辣碎，加入鸡瓜翻炒均匀",
        "加如生抽，老抽，耗油，翻炒均匀加水没过鸡爪",
        "大火煮沸后转小火30分钟即可，撒葱花出锅",
      ],
      "seasoning": [],
      "support": [],
    },
    {
      "id": 94,
      "name": "肉末豆角",
      "type": "肉类",
      "img": 'https://i04piccdn.sogoucdn.com/a557f984da8cc52f',
      "time": '',
      "mainFood": [
        "豆角",
        "小米辣",
        "肉末",
      ],
      "prepare": [
        "肉末拿出来化了",
        "葱花",
        "小米辣切段",
        "蒜末",
        "豆角洗干净切碎块",
        "调汁：2勺生抽，1勺老抽，1勺料酒，1勺耗油，半勺白糖，半碗水",
      ],
      "step": [
        "起锅烧油，炒熟肉末",
        "倒入调好的酱汁，煮开盛出",
        "起锅烧油，加葱蒜小米辣，放入豆角碎，多炒会儿",
        "加入炒好的肉末搅拌均匀出锅",
      ],
      "seasoning": [],
      "support": [],
    },
    {
      "id": 95,
      "name": "砂锅土豆粉",
      "type": "主食",
      "img": 'https://i01piccdn.sogoucdn.com/5b93b5b87e46a998',
      "time": '',
      "mainFood": [
        "土豆粉",
        "火锅底料",
      ],
      "prepare": [
        "准备小碗放 :葱末,蒜末,火锅底料掰一小块,豆瓣酱一勺",
        "爱吃的火锅丸子拿出来化了(可有可无)",
        "青菜洗干净(可有可无)",
        "海带丝豆芽金针菇豆皮准备好(可有可无)"
      ],
      "step": [
        "热适量油 把葱蒜炒香，加一勺豆瓣酱和一小块火锅底料",
        "炒出红油加入适量清水，大火煮开",
        "下入爱吃的丸子各种配菜 eg: 火锅丸子，金针菇，海带丝，豆芽，豆腐皮等",
        "加入生抽，陈醋，鸡精，胡椒粉",
        "盖盖煮2分钟，放入土豆粉和青菜，淋上香油可以开吃",
      ],
      "seasoning": [],
      "support": [],
    },
    {
      "id": 96,
      "name": "炸辣椒油",
      "type": "零食",
      "img": 'https://i03piccdn.sogoucdn.com/e0da847633fd8f4a',
      "time": '',
      "mainFood": [
        "洋葱",
        "香菜",
      ],
      "prepare": [
        "洋葱切块",
        "香料碗中放入： 葱段，姜片，桂皮，花椒，八角，香叶，洋葱，香菜",
        "大一点的辣椒碗(碗里无水)： 碗中放入 粗辣椒粉，洗辣椒粉，白芝麻，一勺食用油 搅拌均匀",
      ],
      "step": [
        "锅中放大量油(就是你想炸多少辣椒油出来的量)",
        "低温下入准备好的香料碗中的所有东西",
        "小火慢炸，将所有调料榨干捞出",
        "接着开大火，升高油温，等到油开始冒白烟，分三次倒入准备好的辣椒碗每次都要充分搅拌",
        "最后加入少许陈醋，这时候油会产生激烈反应，用筷子搅合均匀"
      ],
      "seasoning": [],
      "support": [],
    },
    {
      "id": 97,
      "name": "鲜奶麻薯",
      "type": "甜品",
      "img": 'https://i03piccdn.sogoucdn.com/6700b6280bc67eb7',
      "time": '',
      "mainFood": [
        "木薯淀粉",
        "牛奶",
        "黄豆粉",
      ],
      "prepare": [
        "木薯淀粉20g",
        "纯牛奶200g",
        "白糖15g",
      ],
      "step": [
        "锅中放牛奶+白糖+木薯淀粉搅拌均匀，小火加热，变加热变搅拌至浓稠",
        "裹上黄豆粉，剪成小份即可",
      ],
      "seasoning": [],
      "support": [],
    },
    {
      "id": 98,
      "name": "焦糖补丁",
      "type": "甜品",
      "img": 'https://i01piccdn.sogoucdn.com/abbf245617e1377d',
      "time": '',
      "mainFood": [
        "鸡蛋",
        "牛奶",
        "淡奶油",
        // "筛子"
      ],
      "prepare": [
        "大碗放蛋黄5个 + 30g糖",
        "牛奶170g",
        "淡奶油170g",
      ],
      "step": [
        "蛋黄+砂糖搅拌均匀，牛奶+淡奶油倒入锅中，小火加热至边缘旗袍，缓缓倒入蛋黄液中，一边倒一边搅拌，直到混合均匀",
        "过筛两遍，倒入纸杯模具，烤盘内加水，放入模具，烤箱预热后，上下火180度烤15分钟",
        "表面微微上色，取出撒一层糖，继续烤10分钟即可",
      ],
      "seasoning": [],
      "support": [],
    },
    {
      "id": 99,
      "name": "吐司面包",
      "type": "甜品",
      "img": 'https://i04piccdn.sogoucdn.com/d469c960bf98836f',
      "time": '',
      "mainFood": [
        "鸡蛋",
        "牛奶",
        "淡奶油",
        // "筛子"
      ],
      "prepare": [
        "大碗放蛋黄5个 + 30g糖",
        "牛奶170g",
        "淡奶油170g",
      ],
      "step": [
        "蛋黄+砂糖搅拌均匀，牛奶+淡奶油倒入锅中，小火加热至边缘旗袍，缓缓倒入蛋黄液中，一边倒一边搅拌，直到混合均匀",
        "过筛两遍，倒入纸杯模具，烤盘内加水，放入模具，烤箱预热后，上下火180度烤15分钟",
        "表面微微上色，取出撒一层糖，继续烤10分钟即可",
      ],
      "seasoning": [],
      "support": [],
    },
    {
      "id": 100,
      "name": "蛋挞",
      "type": "甜品",
      "img": 'https://i01piccdn.sogoucdn.com/3514a27094755af9_adv',
      "time": '',
      "mainFood": [
        "鸡蛋",
        "牛奶",
        "淡奶油",
      ],
      "prepare": [
        "大碗放鸡蛋2个 + 16g糖 + 炼乳(没有炼乳加22g糖)",
        "牛奶50g",
        "淡奶油100g",
      ],
      "step": [
        "此配方适合6个蛋挞皮",
        "只用蛋黄且过筛会更细腻",
        "预热烤箱435°F, 烤20分钟",
      ],
      "seasoning": [],
      "support": [],
    },
    {
      "id": 101,
      "name": "五花肉炒娃娃菜",
      "type": "肉类",
      "img": 'https://i01piccdn.sogoucdn.com/d64edd1d7df4cac9_adv',
      "time": '',
      "mainFood": [
        "五花肉",
        "娃娃菜",
        "小米辣",
      ],
      "prepare": [
        "五花肉切块",
        "娃娃菜切块",
      ],
      "step": [
        "放油，炒香小米辣",
        "倒入五花肉，炒出油脂",
        "加1勺生抽，盐 翻炒",
        "倒入娃娃菜炒软出过",
      ],
      "seasoning": [],
      "support": [],
    },
    {
      "id": 102,
      "name": "麻辣毛肚冒菜",
      "type": "肉类",
      "img":
          'https://cp1.douguo.com/upload/caiku/5/4/2/yuan_54bbf133968a720829a5d4dfa52e9f42.jpeg',
      "time": '',
      "mainFood": [
        "毛肚",
        "豆芽",
        "午餐肉",
        "火锅底料",
      ],
      "prepare": [
        "大葱切块",
        "姜切片",
        "干辣椒切块",
        "切蒜末",
        "午餐肉切片",
        "洗切喜欢的青菜",
      ],
      "step": [
        "放适量多点油，炒香大葱，姜，花椒，干辣椒",
        "炒香后放入两块麻辣火锅底料",
        "融化后，加一勺豆瓣酱炒出红油，倒入半锅清水",
        "加2勺生抽，1勺鸡精，1勺白糖，1勺胡椒粉",
        "水开后盛出料渣，放入备菜，豆芽青菜打底，五分钟捞出",
        "下入豆干，午餐肉，3分钟捞出",
        "最后放入毛肚，烫个20s就可以捞出装盘，加入原汤",
        "制作辣油：蒜末，细辣椒粉，粗辣椒粉，孜然粉，白芝麻，淋上热油",
        "把辣油倒在毛肚上",
        "撒上葱花",
      ],
      "seasoning": [],
      "support": [],
    },
    {
      "id": 103,
      "name": "青椒炒肉丝烩饭",
      "type": "主食",
      "img": 'https://i02piccdn.sogoucdn.com/896a95629dee1500',
      "time": '',
      "mainFood": [
        "青椒",
        "猪瘦肉",
      ],
      "prepare": [
        "猪瘦肉切丝",
        "青椒切丝",
        "切蒜末",
        "腌制肉丝加入少许油，生抽，胡椒粉，寂静，淀粉，抓匀腌制15分钟",
        "调酱汁: 1勺耗油，少许盐，1勺淀粉，半碗水",
      ],
      "step": [
        "热油放入肉丝炒至变色，加入青椒蒜末爆香",
        "倒入酱汁和米饭，煮至浓稠即可",
      ],
      "seasoning": [],
      "support": [],
    },
    {
      "id": 104,
      "name": "口蘑牛肉炒饭",
      "type": "主食",
      "img": 'https://i03piccdn.sogoucdn.com/a76175a4d068db1c',
      "time": '',
      "mainFood": [
        "口蘑",
        "洋葱",
        "牛肉",
        "蒜",
        "剩饭",
      ],
      "prepare": [
        "口蘑切块",
        "洋葱切碎",
        "蒜末",
        "葱花",
        "牛肉切粒，倒入 1.5勺生抽，半勺老抽，少许黑胡椒，一勺糖",
      ],
      "step": [
        "少许油，热油放口蘑翻炒，加洋葱碎，蒜末",
        "放入牛肉粒，翻炒后倒入米饭，大火翻炒后加葱花出锅",
      ],
      "seasoning": [],
      "support": [],
    },
    {
      "id": 105,
      "name": "麻辣拌减脂餐",
      "type": "减脂",
      "img": 'https://i01piccdn.sogoucdn.com/4066bb98216eb47e',
      "time": '',
      "mainFood": [
        "虾",
        "干豆腐",
        "海带丝",
        "金针菇",
        "生菜",
        "木耳",
      ],
      "prepare": [
        "葱花",
        "辣油: 蒜末,辣椒粉，白芝麻，孜然粉 淋热油 + 2勺生抽，半勺花椒油，2勺陈醋",
      ],
      "step": [
        "把所有食材煮熟，和辣油拌一起即可",
      ],
      "seasoning": [],
      "support": [],
    },
    {
      "id": 106,
      "name": "红烧排骨",
      "type": "肉类",
      "img": 'https://i01piccdn.sogoucdn.com/4aab93b1708dd517_adv',
      "time": '',
      "mainFood": [
        "排骨",
      ],
      "prepare": ["配料：葱切大块，姜切片，干辣椒，2个八角，香叶,桂皮，冰糖"],
      "step": [
        "锅中放冷水，下排骨，放料酒，煮熟，去沫，捞出，过凉水洗干净，控干水分",
        "起锅烧油，加入冰糖，熬糖色，下排骨，翻炒上色",
        "加入所有配料，翻炒后加料酒，生抽，老抽，耗油，翻炒均匀后加水",
        "加盐，鸡精，十三香，盖盖子，大火转小火炖40分钟",
        "大火收汁,出锅",
      ],
      "seasoning": [],
      "support": [],
    },
  ];
}

test() {
  return {
    "id": 0,
    "name": "",
    "type": "",
    "img": '',
    "time": '',
    "mainFood": [
      "",
      "",
      "",
      "",
    ],
    "prepare": [
      "",
      "",
      "",
      "",
      "",
    ],
    "step": [
      "",
      "",
      "",
      "",
      "",
    ],
    "seasoning": [],
    "support": [],
  };
}
